import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/.turbo/**',
      '**/next-env.d.ts',
      // Generated by `prisma generate`. Linting it reports on Prisma's code
      // style, which nobody in this repository can act on.
      'apps/api/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      globals: { ...globals.node },
      // Type-aware linting. `projectService` picks the nearest tsconfig per file,
      // which is what a workspace with one tsconfig per package needs.
      // `no-floating-promises` alone justifies the slower run in a codebase that
      // will be full of queue producers.
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Plain JavaScript is outside every tsconfig, so the type-aware rules have no
  // program to work from and must be switched off for it.
  {
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },

  // Tooling config files are CommonJS; the flat-config default of ESM would
  // flag `module.exports`. `require` is how CommonJS imports, so the rule
  // telling it not to has nothing to suggest here.
  {
    files: ['**/*.config.js', '**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },

  {
    files: ['apps/api/**/*.spec.ts', 'apps/api/**/*.int-spec.ts'],
    languageOptions: { globals: { ...globals.jest } },
  },

  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // App Router only — this rule looks for a `pages/` directory that will
      // never exist and warns on every run.
      '@next/next/no-html-link-for-pages': 'off',
      /*
       * The workflow canvas library is ~59 KB gzipped and belongs to two routes.
       * A single static import anywhere else — including from a test helper a
       * barrel re-exports — puts it on every console route, and the leak would
       * be invisible until somebody read a bundle report. TAR-809 asks for the
       * containment to be enforced rather than trusted; this is that.
       *
       * The one module allowed to import it is exempted below.
       */
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@xyflow/react', '@xyflow/react/*'],
              message:
                'Import @xyflow/react only from features/workflows/components/WorkflowCanvas.tsx, which is behind workflow-canvas.lazy.tsx. See TAR-809 Decision 1.',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['apps/web/features/workflows/components/WorkflowCanvas.tsx'],
    rules: { 'no-restricted-imports': 'off' },
  },

  // Must stay last: turns off every rule that fights Prettier.
  prettier,
);
